name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    # - name: Git Semantic Version
    #   uses: PaulHatch/semantic-version@v4.0.3
    #   with:
    #     major_pattern: "major:"
    #     minor_pattern: "feat:"
    #     format: "${major}.${minor}.${patch}-prerelease${increment}"
    #   id: version

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        patch_pattern: "fix:"
        format: "V-${major}.${minor}.${patch}"
        # format: "${major}.${minor}.${patch}-prerelease${increment}"
        tag_prefix: "v"  # Si usas tags como v1.0.0
        namespace: ""    # Namespace para tags
        bump_each_commit: true
        search_commit_body: false  # Solo busca en el t√≠tulo del commit
      id: version
      
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        

    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t fgil35/graphq-docker:$NEW_VERSION .
        docker build -t fgil35/graphq-docker:latest .
        echo "New version: $NEW_VERSION"
        
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push fgil35/graphq-docker:$NEW_VERSION
        docker push fgil35/graphq-docker:latest
        echo "New version: $NEW_VERSION"
        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
